### ISSUE TITLE
List of commission siglas/abbreviations

### ISSUE THREAD

**Issue by RobertMyles** [RobertMyles/congressbr#6]
A list of siglas of the comissões would be great, I have no idea how to get that. If it's short, it could just be printed to the console as a function, even. If not, maybe a data frame, although I don't want to add too much data to the package.

**Comment by danilofreire** [comment]
Sure, I'll look into it after I finish issues [#2](https://github.com/RobertMyles/congressbr/issues/2) and [#5](https://github.com/RobertMyles/congressbr/issues/5). Although I know #5 is not a priority, I might start with it because it's the easiest. I can probably get it done in a day.

Do you prefer it as a function? Having the list as a data frame is easier, indeed, but maybe not so convenient.  I'll think about how to do that.

**Comment by RobertMyles** [comment]
A problem here is that commissions can change... there are the [permanent ones](http://www12.senado.leg.br/noticias/glossario-legislativo/comissoes-permanentes) and then there are temporary ones. I can put in the permanent ones now, but I'm not sure what to do about the temp ones.

**Comment by RobertMyles** [comment]
Hmmm, maybe we could print to the console the permanent ones? Then maybe for a complete list, we put them all in a dataframe and add it as data.

**Comment by RobertMyles** [comment]
It's available in `data("commissions")`.
